import http2 from 'node:http2';

const {
    HTTP_STATUS_OK,
    HTTP_STATUS_CREATED,
    HTTP_STATUS_BAD_REQUEST,
    HTTP_STATUS_UNAUTHORIZED,
    HTTP_STATUS_FORBIDDEN,
    HTTP_STATUS_NOT_FOUND,
    HTTP_STATUS_CONFLICT,
    HTTP_STATUS_INTERNAL_SERVER_ERROR,
} = http2.constants;

const ResponseCodes = Object.freeze({
    PAYLOAD: Object.freeze({
        SUCCESS: HTTP_STATUS_OK,
        CREATED: HTTP_STATUS_CREATED,
        BAD_REQUEST: HTTP_STATUS_BAD_REQUEST,
        UNAUTHORIZED: HTTP_STATUS_UNAUTHORIZED,
        FORBIDDEN: HTTP_STATUS_FORBIDDEN,
        NOT_FOUND: HTTP_STATUS_NOT_FOUND,
        CONFLICT: HTTP_STATUS_CONFLICT,
        INTERNAL_ERROR: HTTP_STATUS_INTERNAL_SERVER_ERROR,
    }),

    SUCCESS: HTTP_STATUS_OK,
    CREATED: HTTP_STATUS_OK,

    BAD_REQUEST: HTTP_STATUS_OK,
    UNAUTHORIZED: HTTP_STATUS_OK,
    FORBIDDEN: HTTP_STATUS_OK,
    NOT_FOUND: HTTP_STATUS_OK,
    CONFLICT: HTTP_STATUS_OK,

    INTERNAL_ERROR: HTTP_STATUS_INTERNAL_SERVER_ERROR,
});

export default ResponseCodes;
